# Generated by Django 4.1.3 on 2023-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoo_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
