# Generated by Django 4.1.3 on 2023-02-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todoo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todoo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todoo',
            name='user',
        ),
    ]
