# Generated by Django 4.1.3 on 2023-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_todoo_created_remove_todoo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='close',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
